# Generated by Django 6.0.7 on 2026-08-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='lineitem_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
