# Generated by Django 6.0.7 on 2026-08-23 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_review_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
